--options sep_char=; generation_time=Thu Mar 30 14:51:23 2017


CREATE INDEX "CMDELIL7" ON "CMDELIP" ( "CLOPSUP" ASC, "CLCDINTYP" ASC, 
"CLNOCMD" ASC, "CLNOLIGCMD" ASC, "CLNOSLICMD" ASC);
LABEL ON INDEX "CMDELIL7" IS 
'CLOPSUP, CLCDINTYP, CLNOCMD, CLNOLIGCMD, CLNOSLICM';

