--options sep_char=; generation_time=Thu Mar 30 14:51:44 2017


CREATE INDEX "CMDELIL9" ON "CMDELIP" ( "CLOPSUP" ASC, "CLNOSLICMD" ASC, 
"CLNOCMD" ASC, "CLNOLIGCMD" ASC);
LABEL ON INDEX "CMDELIL9" IS 'CLOPSUP, CLNOSLICMD, CLNOCMD, CLNOLIGCMD';

