--options sep_char=; generation_time=Thu Mar 30 14:51:56 2017


CREATE INDEX "CMDELIL10" ON "CMDELIP" ( "CLOPSUP" ASC, "CLCDINTYP" ASC, 
"CLNOCMD" ASC, "CLCDPRODIN" ASC, "CLNOSLICMD" ASC);
LABEL ON INDEX "CMDELIL10" IS 
'CLOPSUP, CLCDINTYP, CLNOCMD, CLCDPRODIN, CLNOSLICM';

