--options sep_char=; generation_time=Thu Mar 30 14:51:35 2017


CREATE INDEX "CMDELIL8" ON "CMDELIP" ( "CLOPSUP" ASC, "CLNOSLICMD" ASC, 
"CLNOCMD" ASC, "CLCDINTPAR" ASC);
LABEL ON INDEX "CMDELIL8" IS 'CLOPSUP, CLNOSLICMD, CLNOCMD, CLCDINTPAR';

