-- Table CMDRLCP (Création)

CREATE TABLE "CMDRLCP" (
 "R4NOINTREC" DEC(9, 0) NOT NULL WITH DEFAULT,
 "R4NOINGLGR" DEC(5, 0) NOT NULL WITH DEFAULT,
 "R4NODOCREC" DEC(9, 0) NOT NULL WITH DEFAULT,
 "R4NOLGDOCR" DEC(5, 0) NOT NULL WITH DEFAULT,
 "R4QRSTRAPR" DEC(10, 0) NOT NULL WITH DEFAULT,
 "R4QTREGUL" DEC(10, 0) NOT NULL WITH DEFAULT,
 "R4TPLITR" CHAR(1) NOT NULL WITH DEFAULT,
 "R4MOTSLD" CHAR(3) NOT NULL WITH DEFAULT,
 "R4QTESLD" DEC(10, 0) NOT NULL WITH DEFAULT,
 "R4OPCRE" CHAR(10) NOT NULL WITH DEFAULT,
 "R4DTCRE" DATE NOT NULL WITH DEFAULT,
 "R4HECRE" TIME NOT NULL WITH DEFAULT,
 "R4OPMOD" CHAR(10) NOT NULL WITH DEFAULT,
 "R4DTMOD" DATE NOT NULL WITH DEFAULT,
 "R4HEMOD" TIME NOT NULL WITH DEFAULT,
 "R4OPSOLD" CHAR(10) NOT NULL WITH DEFAULT,
 "R4DTSOLD" DATE NOT NULL WITH DEFAULT,
 "R4HESOLD" TIME NOT NULL WITH DEFAULT,
 "R4OPSUP" CHAR(10) NOT NULL WITH DEFAULT,
 "R4DTSUP" DATE NOT NULL WITH DEFAULT,
 "R4HESUP" TIME NOT NULL WITH DEFAULT,
 PRIMARY KEY ("R4NOINTREC" ,"R4NOINGLGR"));

LABEL ON TABLE "CMDRLCP" IS 'Complément ligne de réception';

LABEL ON "CMDRLCP" (
 "R4NOINTREC" IS 'Numéro interne de   réception',
 "R4NOINGLGR" IS 'N° ligne',
 "R4NODOCREC" IS 'Numéro de           document interne',
 "R4NOLGDOCR" IS 'N° ligne de document',
 "R4QRSTRAPR" IS 'Quantité restant à  rapprocher réception',
 "R4QTREGUL" IS 'Quantité régularisée(OD-)',
 "R4TPLITR" IS 'Top litige réceptionO/N',
 "R4MOTSLD" IS 'Motif solde         réception',
 "R4QTESLD" IS 'Quantité soldée',
 "R4OPCRE" IS 'Opérateur création',
 "R4DTCRE" IS 'Date création',
 "R4HECRE" IS 'Heure création',
 "R4OPMOD" IS 'Opérateur           modification',
 "R4DTMOD" IS 'Date modification',
 "R4HEMOD" IS 'Heure modification',
 "R4OPSOLD" IS 'Opérateur de solde',
 "R4DTSOLD" IS 'Date de solde',
 "R4HESOLD" IS 'Heure de solde',
 "R4OPSUP" IS 'Opérateur           suppression',
 "R4DTSUP" IS 'Date suppression',
 "R4HESUP" IS 'Heure suppression');

LABEL ON "CMDRLCP" (
 R4NOINTREC TEXT IS 'Numéro interne de réception',
 R4NOINGLGR TEXT IS 'N° ligne réception',
 R4NODOCREC TEXT IS 'Numéro de document interne',
 R4NOLGDOCR TEXT IS 'N° ligne de document',
 R4QRSTRAPR TEXT IS 'Quantité restant à rapprocher réception',
 R4QTREGUL TEXT IS 'Quantité régularisée (OD-)',
 R4TPLITR TEXT IS 'Top litige réception O/N',
 R4MOTSLD TEXT IS 'Motif solde réception',
 R4QTESLD TEXT IS 'Quantité soldée',
 R4OPCRE TEXT IS 'Opérateur création',
 R4DTCRE TEXT IS 'Date création',
 R4HECRE TEXT IS 'Heure création',
 R4OPMOD TEXT IS 'Opérateur modification',
 R4DTMOD TEXT IS 'Date modification',
 R4HEMOD TEXT IS 'Heure modification',
 R4OPSOLD TEXT IS 'Opérateur de solde',
 R4DTSOLD TEXT IS 'Date de solde',
 R4HESOLD TEXT IS 'Heure de solde',
 R4OPSUP TEXT IS 'Opérateur suppression',
 R4DTSUP TEXT IS 'Date suppression',
 R4HESUP TEXT IS 'Heure suppression');

