--options sep_char=; generation_time=Thu Mar 30 14:45:34 2017


CREATE INDEX "CMDRLCL2" ON "CMDRLCP" ( "R4NOINTREC" ASC, "R4NOINGLGR" ASC, 
"R4NODOCREC" ASC, "R4NOLGDOCR" ASC);
LABEL ON INDEX "CMDRLCL2" IS 'R4NOINTREC, R4NOINGLGR, R4NODOCREC, R4NOLGDOCR';

