-- Table I9DAPEP (Création)

CREATE TABLE "I9DAPEP" (
 "EIDINDAE" CHAR(17) NOT NULL WITH DEFAULT,
 "EIDSRDAP" CHAR(4),
 "EIDLFDAP" CHAR(4),
 "EIDCLRDAP" CHAR(4),
 "ECDACTDAP" DEC(1, 0),
 "ETYBLLDAP" DEC(2, 0),
 "ETYBLCDAP" DEC(2, 0),
 "ECDDESDAP" CHAR(20),
 "ENUORDDAP" DEC(9, 0),
 "EDTLIVDAP" DATE,
 "ETYDLDAP" DEC(2, 0),
 "EINGRDAP" DEC(1, 0),
 "EPRPCDDAP" DEC(3, 0),
 "EINDCCDAP" DEC(1, 0),
 "ETYDCEDAP" DEC(2, 0),
 "EVADCDAP" DEC(2, 0),
 "ETYPBLDAP" DEC(2, 0),
 "ENBDCDAP" DEC(2, 0),
 "ERFCDEDAP" CHAR(35),
 "ERFCHDAP" CHAR(35),
 "EMDTRODAP" CHAR(35),
 "ECDDVDAP" CHAR(3),
 "ETPCDCDAP" DEC(1, 0),
 "ECDRGTDAP" DEC(2, 0),
 "ETYEXDAP" DEC(2, 0),
 "ECDTRIDAP" CHAR(20),
 "ECDTNIDAP" CHAR(20),
 "ECDADLDAP" CHAR(20),
 "ELBADLDAP" CHAR(38),
 "EADLI1DAP" CHAR(38),
 "EADLI2DAP" CHAR(38),
 "EADLI3DAP" CHAR(38),
 "EADLI4DAP" CHAR(38),
 "ECDPOLDAP" CHAR(10),
 "EBULVDAP" CHAR(35),
 "ECDPALDAP" CHAR(2),
 "ELBADFDAP" CHAR(38),
 "EADFA1DAP" CHAR(38),
 "EADFA2DAP" CHAR(38),
 "EADFA3DAP" CHAR(38),
 "EADFA4DAP" CHAR(38),
 "ECDPOFDAP" CHAR(10),
 "EBUFADAP" CHAR(35),
 "ECDPAFDAP" CHAR(2),
 "ECDVEDAP" DEC(4, 0),
 "ENMVEDAP" CHAR(35),
 "ECDTCIAP" CHAR(4),
 "EIDTX1DAP" DEC(1, 0),
 "ETXTV1DAP" DEC(7, 3),
 "EIDTV2DAP" DEC(1, 0),
 "ETXTV2DAP" DEC(7, 3),
 "EIDTV3DAP" DEC(1, 0),
 "ETXTV3DAP" DEC(7, 3),
 "ENBLIDAP" DEC(4, 0),
 "ENBCMTDAP" DEC(4, 0),
 "EDHCREDAP" TIMESTAMP,
 "EDHTRTDAP" TIMESTAMP,
 "EINGERDAP" DEC(1, 0),
 "ECDCLCDAP" CHAR(11),
 "ENUCDADAP" DEC(9, 0),
 "ESTTRTDAP" DEC(1, 0),
 "ENUCDODAP" DEC(9, 0),
 "ECALLVHEB" CHAR(7),
 "ECTCJNO" DEC(1, 0),
 "EIDLFLIV" CHAR(4),
 "ECDSRVLDAP" NUMERIC(2, 0),
 "ECONLIVDAP" CHAR(50),
 "EINDTELDAP" CHAR(3),
 "ENOTELDAP" CHAR(20),
 "ECDTYPLOG" CHAR(5),
 "ECDPRESDAP" CHAR(20),
 "ETPBLLOGTB" DEC(9, 0),
 "ETPDCAEDTB" DEC(9, 0),
 "ETPPRBLVTB" DEC(9, 0),
 "ECDREGTRTB" DEC(9, 0),
 "ETPDTLIVTB" DEC(9, 0),
 "EINDGRPTB" DEC(9, 0),
 "EVARDOCTB" DEC(9, 0),
 "EMODTRORTB" DEC(9, 0),
 "ETPEXPTB" DEC(9, 0));

LABEL ON TABLE "I9DAPEP" IS 'Table des WebServices des DAP entête';

LABEL ON "I9DAPEP" (
 "EIDINDAE" IS 'Identifiant de      l''interface',
 "EIDSRDAP" IS 'Identifiant SR',
 "EIDLFDAP" IS 'Identifiant LF',
 "EIDCLRDAP" IS 'Identifiant CL',
 "ECDACTDAP" IS 'Code action',
 "ETYBLLDAP" IS 'Type BL logistique',
 "ETYBLCDAP" IS 'Type BL commercial',
 "ECDDESDAP" IS 'Code destinataire',
 "ENUORDDAP" IS 'N° d''ordre initial',
 "EDTLIVDAP" IS 'Date de livraison   prévue pour         commandes clients',
 "ETYDLDAP" IS 'Type de délai',
 "EINGRDAP" IS 'Indicateur de       groupage',
 "EPRPCDDAP" IS 'Priorité de         préparation de      la commande',
 "EINDCCDAP" IS 'Indicateur document en double contrôle',
 "ETYDCEDAP" IS 'Type de document    à éditer',
 "EVADCDAP" IS 'Variante de         document',
 "ETYPBLDAP" IS 'Type de présentationdu BL valorisé',
 "ENBDCDAP" IS 'Nombre d''exemplairesde documents        à éditer',
 "ERFCDEDAP" IS 'Référence commande',
 "ERFCHDAP" IS 'Référence chantier',
 "EMDTRODAP" IS 'Mode transmission   de l''ordre          par le destinataire',
 "ECDDVDAP" IS 'Code devise du pays',
 "ETPCDCDAP" IS 'Motif orientation   de stock',
 "ECDRGTDAP" IS 'Code régime         de transport',
 "ETYEXDAP" IS 'Type export',
 "ECDTRIDAP" IS 'Code transporteur   imposé',
 "ECDTNIDAP" IS 'Code tournée        de transport imposé',
 "ECDADLDAP" IS 'Code adresse        de livraison',
 "ELBADLDAP" IS 'Raison sociale      adresse de livraison',
 "EADLI1DAP" IS 'Ligne 1 adresse     livraison',
 "EADLI2DAP" IS 'Ligne 2 adresse     livraison',
 "EADLI3DAP" IS 'Ligne 3 adresse     livraison',
 "EADLI4DAP" IS 'Ligne 4 adresse     livraison',
 "ECDPOLDAP" IS 'Code postal         de livraison',
 "EBULVDAP" IS 'Bureau de livraison',
 "ECDPALDAP" IS 'Code pays           de livraison',
 "ELBADFDAP" IS 'Raison sociale      adresse de          facturation',
 "EADFA1DAP" IS 'Ligne 1 adresse     de facturation',
 "EADFA2DAP" IS 'Ligne 2 adresse     de facturation',
 "EADFA3DAP" IS 'Ligne 3 adresse     de facturation',
 "EADFA4DAP" IS 'Ligne 4 adresse     de facturation',
 "ECDPOFDAP" IS 'Code postal         de facturation',
 "EBUFADAP" IS 'Bureau facturation',
 "ECDPAFDAP" IS 'Code pays           facturation',
 "ECDVEDAP" IS 'Code vendeur',
 "ENMVEDAP" IS 'Nom vendeur',
 "ECDTCIAP" IS 'Code T.C.I.',
 "EIDTX1DAP" IS 'Identifiant taux    TVA 1',
 "ETXTV1DAP" IS 'Taux de TVA 1',
 "EIDTV2DAP" IS 'Identifiant taux    TVA 2',
 "ETXTV2DAP" IS 'Taux de TVA 2',
 "EIDTV3DAP" IS 'Identifiant taux    de TVA 3',
 "ETXTV3DAP" IS 'Taux de TVA 3',
 "ENBLIDAP" IS 'Nb ligne de commandetransmises dans     le fichier',
 "ENBCMTDAP" IS 'Nb commentaires     transmis',
 "EDHCREDAP" IS 'Date et heure de    création commande',
 "EDHTRTDAP" IS 'Date et heure       de traitement',
 "EINGERDAP" IS 'Indicateur générat° automatique des     reliquats',
 "ECDCLCDAP" IS 'Code client         commercial',
 "ENUCDADAP" IS 'N° cde achat        livraisons intra grpou dem régul',
 "ESTTRTDAP" IS 'Statut de traitement',
 "ENUCDODAP" IS 'Numéro commande     d''origine',
 "ECALLVHEB" IS 'Calendrier livraiso n hebdo',
 "ECTCJNO" IS 'Contrainte calendrier sur Jour non ouvré',
 "EIDLFLIV" IS 'Identifiant LF livré',
 "ECDSRVLDAP" IS 'Code service de     transport (Service  de livraison)',
 "ECONLIVDAP" IS 'Contact livraison',
 "EINDTELDAP" IS 'Indicatif           téléphonique        livraison',
 "ENOTELDAP" IS 'N° tél contact      livraison',
 "ECDTYPLOG" IS 'Typologie logistique',
 "ECDPRESDAP" IS 'Code prestation',
 "ETPBLLOGTB" IS 'Type BL Log',
 "ETPDCAEDTB" IS 'Type document à     éditer',
 "ETPPRBLVTB" IS 'Type présentation duBL valorisé',
 "ECDREGTRTB" IS 'Code régime transpor',
 "ETPDTLIVTB" IS 'Type date de livr',
 "EINDGRPTB" IS 'Indicateur de       groupage',
 "EVARDOCTB" IS 'Variante de document',
 "EMODTRORTB" IS 'Mode de transmissionde l''ordre',
 "ETPEXPTB" IS 'Type export');

LABEL ON "I9DAPEP" (
 EIDINDAE TEXT IS 'ID Interface',
 EIDSRDAP TEXT IS 'Identifiant SR',
 EIDLFDAP TEXT IS 'Identifiant LF',
 EIDCLRDAP TEXT IS 'Identifiant CL',
 ECDACTDAP TEXT IS 'Code action',
 ETYBLLDAP TEXT IS 'Type de BL logistique',
 ETYBLCDAP TEXT IS 'Type de BL commercial',
 ECDDESDAP TEXT IS 'Code destinataire (client, agence)',
 ENUORDDAP TEXT IS 'N° d''ordre initial (commande client)',
 EDTLIVDAP TEXT IS 'Date de livraison prévue pour commandes clients',
 ETYDLDAP TEXT IS 'Type de délai',
 EINGRDAP TEXT IS 'Indicateur de groupage',
 EPRPCDDAP TEXT IS 'Priorité de préparation de la commande',
 EINDCCDAP TEXT IS 'Indicateur document en double contrôle',
 ETYDCEDAP TEXT IS 'Type de document à éditer',
 EVADCDAP TEXT IS 'Variante de document',
 ETYPBLDAP TEXT IS 'Type de présentation du BL valorisé',
 ENBDCDAP TEXT IS 'Nombre d''exemplaires de documents à éditer',
 ERFCDEDAP TEXT IS 'Référence commande',
 ERFCHDAP TEXT IS 'Référence chantier',
 EMDTRODAP TEXT IS 'Mode transmission de l''ordre par le destinataire',
 ECDDVDAP TEXT IS 'Code devise du pays',
 ETPCDCDAP TEXT IS 'Motif orientation de stock',
 ECDRGTDAP TEXT IS 'Code régime de transport',
 ETYEXDAP TEXT IS 'Type export',
 ECDTRIDAP TEXT IS 'Code transporteur imposé',
 ECDTNIDAP TEXT IS 'Code tournée de transport imposé',
 ECDADLDAP TEXT IS 'Code adresse de livraison',
 ELBADLDAP TEXT IS 'Raison sociale adresse de livraison',
 EADLI1DAP TEXT IS 'Ligne 1 adresse livraison',
 EADLI2DAP TEXT IS 'Ligne 2 adresse livraison',
 EADLI3DAP TEXT IS 'Ligne 3 adresse livraison',
 EADLI4DAP TEXT IS 'Ligne 4 adresse livraison',
 ECDPOLDAP TEXT IS 'Code postal de livraison',
 EBULVDAP TEXT IS 'Bureau de livraison',
 ECDPALDAP TEXT IS 'Code pays de livraison',
 ELBADFDAP TEXT IS 'Raison sociale adresse de facturation',
 EADFA1DAP TEXT IS 'Ligne 1 adresse de facturation',
 EADFA2DAP TEXT IS 'Ligne 2 adresse de facturation',
 EADFA3DAP TEXT IS 'Ligne 3 adresse de facturation',
 EADFA4DAP TEXT IS 'Ligne 4 adresse de facturation',
 ECDPOFDAP TEXT IS 'Code postal de facturation',
 EBUFADAP TEXT IS 'Bureau de facturation',
 ECDPAFDAP TEXT IS 'Code pays facturation',
 ECDVEDAP TEXT IS 'Code vendeur',
 ENMVEDAP TEXT IS 'Nom vendeur',
 ECDTCIAP TEXT IS 'Code TCI',
 EIDTX1DAP TEXT IS 'Identifiant taux TVA 1',
 ETXTV1DAP TEXT IS 'Taux de TVA 1',
 EIDTV2DAP TEXT IS 'Identifiant taux TVA 2',
 ETXTV2DAP TEXT IS 'Taux de TVA 2',
 EIDTV3DAP TEXT IS 'Identifiant taux de TVA 3',
 ETXTV3DAP TEXT IS 'Taux de TVA 3',
 ENBLIDAP TEXT IS 'Nb lignes de commande transmises dans le fichier',
 ENBCMTDAP TEXT IS 'Nb commentaires transmis',
 EDHCREDAP TEXT IS 'Date et heure de création commande',
 EDHTRTDAP TEXT IS 'Date et heure de traitement',
 EINGERDAP TEXT IS 'Indicateur génération auto des rlqs (A supprimer)',
 ECDCLCDAP TEXT IS 'Code client commercial',
 ENUCDADAP TEXT IS 'N° cde achat livraisons intra grp ou dem régul',
 ESTTRTDAP TEXT IS 'Statut de traitement',
 ENUCDODAP TEXT IS 'Numéro commande d''origine',
 ECALLVHEB TEXT IS 'Calendrier livraison hebdo',
 ECTCJNO TEXT IS 'Contrainte calendrier sur Jour non ouvré',
 EIDLFLIV TEXT IS 'Identifiant LF livré',
 ECDSRVLDAP TEXT IS 'Code service de transport (Service de livraison)',
 ECONLIVDAP TEXT IS 'Contact livraison',
 EINDTELDAP TEXT IS 'Indicatif téléphonique livraison',
 ENOTELDAP TEXT IS 'N° tél contact livraison',
 ECDTYPLOG TEXT IS 'Typologie logistique',
 ECDPRESDAP TEXT IS 'Code prestation',
 ETPBLLOGTB TEXT IS 'Type BL Log',
 ETPDCAEDTB TEXT IS 'Type document à éditer',
 ETPPRBLVTB TEXT IS 'Type présentation du BL valorisé',
 ECDREGTRTB TEXT IS 'Code régime transport',
 ETPDTLIVTB TEXT IS 'Type date de livraison',
 EINDGRPTB TEXT IS 'Indicateur de groupage',
 EVARDOCTB TEXT IS 'Variante de document',
 EMODTRORTB TEXT IS 'Mode de transmission de l''ordre',
 ETPEXPTB TEXT IS 'Type export');

CREATE INDEX "I9DAPEL2" ON "I9DAPEP" ( "EIDINDAE" ASC, "EIDCLRDAP" ASC, "ESTTRTDAP" ASC, "ECDACTDAP" ASC, "EDHCREDAP" ASC);
LABEL ON INDEX "I9DAPEL2" IS 'Clé : id int, CLR, sta trt, cod act, datheu créa';

CREATE INDEX "I9DAPEL3" ON "I9DAPEP" ( "EIDINDAE" ASC, "EIDCLRDAP" ASC, "ENUORDDAP" ASC);
LABEL ON INDEX "I9DAPEL3" IS 'Clé : id int, CLR, num ord ini';

CREATE INDEX "I9DAPEL4" ON "I9DAPEP" ( "EIDINDAE" ASC);
LABEL ON INDEX "I9DAPEL4" IS 'Clé : id int';

CREATE INDEX "I9DAPEL5" ON "I9DAPEP" ( "EIDINDAE" ASC, "ESTTRTDAP" ASC);
LABEL ON INDEX "I9DAPEL5" IS 'Clé : id int, sta trt';

