-- Création procédure stockée PROSTK_ODV02B

DROP PROCEDURE PROSTK_ODV02B;

CREATE PROCEDURE PROSTK_ODV02B (
 OUT  PCODRET      CHAR (2),
   IN   PCODCL       CHAR (4),
   IN   PCDESNC      NUMERIC (9 , 0),
   IN   PQTEDDE      DECIMAL (10 , 0),
   IN   PDTLIVDDE    date,
   IN   PDTPREDDE    date,
   IN   PCDTYPDEL    DECIMAL (9 , 0),
   IN   PTPMTNRLQ    CHAR (1),
   IN   PCDSITLIV    CHAR (4),
   IN   PCDAPYLIV    CHAR (2),
   IN   PCDPOSLIV    CHAR (10),
   IN   PVILLIV      CHAR(38), 
   IN   PCDMODLIV    CHAR(10), 
   IN   PCDSERLIV    CHAR(10), 
   IN   PTYPLOG      CHAR (5),  
   IN   PCDPRES      CHAR(20), 
   IN   POPTCAL      CHAR (10), 
   OUT  PQTEDAV      DECIMAL (10 , 0),
   OUT  PDTLIV1LV    date, 
   OUT  PDTDIS1LV    date, 
   OUT  PDTPRE1LV    date, 
   OUT  PDTEXP1LV    date, 
   OUT  PPDS1LIV     DECIMAL (9 , 3), 
   OUT  PVOL1LIV     DECIMAL (9 , 3), 
   OUT  PLON1LIV     DECIMAL (9 , 3), 
   OUT  PDTLIVSLR    date, 
   OUT  PDTDISSLR    date, 
   OUT  PDTPRESLR    date, 
   OUT  PDTEXPSLR    date, 
   OUT  PPDSSLR      DECIMAL (9 , 3), 
   OUT  PVOLSLR      DECIMAL (9 , 3), 
   OUT  PLONSLR     DECIMAL (9 , 3), 
   IN   PIDMARCHE    NUMERIC (9, 0),
   IN   PMOTIFOSS    NUMERIC (1, 0),
   IN   PDTLIVFOR    date, 
   IN   PCDAPPSRV    NUMERIC (1 , 0),
   IN   PCDPSTRLQ    CHAR(20), 
   IN   PTPLIVRLQ    CHAR (5), 
   IN   PSRLIVRLQ    NUMERIC (2 , 0), 
   OUT  PQUADELFO    CHAR(5)
  
  )
  
 LANGUAGE RPGLE
 SPECIFIC  PROSTK_ODV02B
NOT DETERMINISTIC
 MODIFIES SQL DATA
CALLED ON NULL INPUT
 EXTERNAL NAME  ODV02B
 PARAMETER STYLE GENERAL  ;