-- Création procédure stockée PROSTK_ODE41B

CREATE PROCEDURE PROSTK_ODE41B
 ( 
 OUT PCODRET CHAR(2) , 
 IN PTRISRC CHAR(3) , 
 IN PCDPRENORD CHAR(4) , 
 IN PNUMCDE NUMERIC(9 , 0) , 
 IN PCDDESTI CHAR(20) , 
 IN PCDCL CHAR(4) , 
 IN PNUMORDINI NUMERIC(9 , 0) , 
 IN PDSIN CHAR(2000) , 
 OUT PIDINT CHAR(17)
 ) 
 DYNAMIC RESULT SETS 1 
 LANGUAGE RPGLE 
 SPECIFIC PROSTK_ODE41B 
 NOT DETERMINISTIC 
 MODIFIES SQL DATA 
 CALLED ON NULL INPUT 
 EXTERNAL NAME ODE41B
 PARAMETER STYLE GENERAL ;