-- Table WCDE10P (Restructuration)

ALTER TABLE WCDE10P ADD COLUMN WWCODAGE CHAR (50) 
NOT NULL WITH DEFAULT BEFORE WWNOPROM;

LABEL ON "WCDE10P" (
 "WWCODAGE" IS 'Code agence',
 "WWNOPROM" IS 'Num promesse');

LABEL ON "WCDE10P" (
 WWCODAGE TEXT IS 'Code agence',
 WWNOPROM TEXT IS 'Num promesse');
