-- Table WCDR10P (Restructuration)

ALTER TABLE WCDR10P ADD COLUMN WWCODAGE CHAR (4) 
NOT NULL WITH DEFAULT BEFORE WWNOPROM;
ALTER TABLE WCDR10P ALTER COLUMN WWPXPAFO 
SET DATA TYPE DEC(13, 5) NOT NULL WITH DEFAULT;

LABEL ON "WCDR10P" (
 "WWCODAGE" IS 'Code agence',
 "WWNOPROM" IS 'Num promesse');

LABEL ON "WCDR10P" (
 WWCODAGE TEXT IS 'Code agence',
 WWNOPROM TEXT IS 'Num promesse');
